spring:
  main:
    banner-mode: off

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:     jdbc:mariadb://localhost:3306/delivery?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

  application:
    name: food-delivery

service:
  jwt:
    access-expiration: 3600 * 60